#! /usr/bin/env python

import sys

sys.path.append('./lib')
import box
import aws

box_name = sys.argv[1]
box_instance_name = sys.argv[2]

data = box.start(box_name, box_instance_name)
ip = data['ip']
aws.ec2_wait_ready(ip)
box.init(ip, box_name, box_instance_name)
